MonitoriaFatec/Controllers/ProfessorController.cs
using MonitoriaFatec.DAO;
using MonitoriaFatec.Filtros;
using MonitoriaFatec.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonitoriaFatec.Controllers
{
    [AutorizacaoFilterAttribute]
    public class ProfessorController : Controller
    {
        // GET: Professor
        public ActionResult Index()
        {
            
            return View();
        }


        public ActionResult Aprovar()
        {
            AtualizaCampos();
            return View();
        }

        public ActionResult Postar()
        {
            AtualizaCampos();
            return View();
        }


        public ActionResult Cadastrar()
        {
            AtualizaCampos();
            return View();
        }

        public ActionResult Logout()
        {
            return RedirectToAction("Index", "Login", "Index");
        }

        public ActionResult PostarMaterial(String titulo, String tipoConteudo, String url, String descricao)
        {
            var usuario = Session["usuarioLogado"] as USUARIO;
            ConteudoDAO daoConteudo = new ConteudoDAO();
            CONTENT conteudo = new CONTENT
            {
                IDAUTHOR = usuario.IDUSER,
                TITLE = titulo,
                IDTYPECONTENT = Int32.Parse(tipoConteudo),
                CONTENT1 = url,
                INFOCONTENT = descricao,
                DATECONTENT = DateTime.Now,
                IDSTATUS = 2
            };
            daoConteudo.Cadastrar(conteudo);
            AtualizaCampos();
            return View("Postar");
        }


        public ActionResult CadastrarMonitor(String idAluno)
        {
            UsuariosDAO daoUsuario = new UsuariosDAO();
            USUARIO usuario = new USUARIO();
            usuario = daoUsuario.BuscaPorId(Int32.Parse(idAluno));
            USUARIO monitor = new USUARIO
            {
                NMUSER = usuario.NMUSER,
                EMAILUSER = idAluno + "@monitor.com",
                USERPASSWORD = idAluno + "@monitor.com" + "1234",
                IDSCOPE = 5
            };
            daoUsuario.Cadastra(monitor);
            AtualizaCampos();
            return View("Cadastrar");
        }

        public void AtualizaCampos()
        {
            UsuariosDAO daoUsuarios = new UsuariosDAO();
            IList<USUARIO> alunos = daoUsuarios.ListaPorEscopo(5);
            ViewBag.Alunos = alunos;

            TipoConteudoDAO daoTipoConteudo = new TipoConteudoDAO();
            IList<TYPECONTENT> tiposConteudo = daoTipoConteudo.Lista();
            ViewBag.TiposConteudo = tiposConteudo;


            ConteudoDAO daoConteudo = new ConteudoDAO();
            var conteudos = daoConteudo.Lista();
            ViewBag.Conteudos = conteudos;

        }
    }
}

MonitoriaFatec/Views/Professor/Aprovar.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Professor!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Professor")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Postar", "Professor")"><i class="fa fa-fw fa-book"></i>Postar Materiais</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link " href="@Url.Action("Aprovar", "Professor")"><i class="fa fa-fw fa-table"></i>Aprovar Conteudo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastrar", "Professor")"><i class="fa fa-fw fa-edit"></i>Habilitar Monitor</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Logout", "Professor")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Professor</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-success o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">
                            11 Novos Materiais!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
    
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

    <div class="container">
        <h2>Aprovar Conteudo</h2>
        <p>Conteudos Pendentes</p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Autor</th>
                        <th>Titulo</th>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th>Status</th>
                        <th>URL</th>
                        <th>Aprovar</th>
                        <th>Reprovar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var material in ViewBag.Conteudos)
                {

                    <tr>
                        <td>@material.IDAUTHOR</td>
                        <td>@material.TITLE</td>
                        <td>@material.INFOCONTENT</td>
                        <td>@material.DATECONTENT</td>
                        <td>@material.IDSTATUS</td>
                        <td>@material.CONTENT1</td>
                        <td>Aprovar</td>
                        <td>Reprovar</td>
                    </tr>
                }
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

MonitoriaFatec/Views/Professor/Cadastrar.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Professor!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Professor")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Postar", "Professor")"><i class="fa fa-fw fa-book"></i>Postar Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Aprovar", "Professor")"><i class="fa fa-fw fa-table"></i>Aprovar Conteudo</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Cadastrar", "Professor")"><i class="fa fa-fw fa-edit"></i>Habilitar Monitor</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Logout", "Professor")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Professor</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-success o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">
                            11 Novos Materiais!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
    
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
    <div class="container-fluid">
        <form action="/Professor/CadastrarMonitor" method="post">

            <label for="inputReciver">Aluno:</label>
            <select class="form-control"  name="idAluno">
                @foreach (var aluno in ViewBag.Alunos)
                {
                    <option value="@aluno.IDUSER">@aluno.NMUSER</option>
                }
            </select>
           
            <br />
            <button class="btn btn-primary" type="submit">Enviar</button>
            @*<input class="btn-primary" type="submit" value="Enviar" />*@
        </form>
    </div>
    
    <br />
    <br />
    <br />
    <div class="container">
        <h2>Monitor Cadastrado</h2>
        
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Excluir</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td>Excluir</td>
                       
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

MonitoriaFatec/Views/Professor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Professor!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Professor")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Postar", "Professor")"><i class="fa fa-fw fa-book"></i>Postar Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Aprovar", "Professor")"><i class="fa fa-fw fa-table"></i>Aprovar Conteudo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastrar", "Professor")"><i class="fa fa-fw fa-edit"></i>Habilitar Monitor</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Logout", "Professor")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Professor</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-success o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">
                            11 Novos Materiais!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
    
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>

MonitoriaFatec/Views/Professor/Postar.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Professor!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Professor")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link " href="@Url.Action("Postar", "Professor")"><i class="fa fa-fw fa-book"></i>Postar Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Aprovar", "Professor")"><i class="fa fa-fw fa-table"></i>Aprovar Conteudo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastrar", "Professor")"><i class="fa fa-fw fa-edit"></i>Habilitar Monitor</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Logout", "Professor")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>

    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Professor</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-success o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">
                            11 Novos Materiais!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>

            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
   
    <div class="container-fluid">
        <form action="/Professor/PostarMaterial" method="post">
            <h3>Postar Material</h3>
            <label for="tipoConteudo">Tipo de Conteudo</label>
            <select class="form-control" name="tipoConteudo">
                @foreach (var tipoConteudo in ViewBag.TiposConteudo)
                {
                    <option value="@tipoConteudo.IDTYPECONTENT">@tipoConteudo.NMTYPECONTENT</option>
                }

            </select>
            <label for="titulo">Titulo</label>
            <input type="text" name="titulo" id="titulo" class="form-control" required="" autofocus="" style="background-repeat: no-repeat; background-attachment: scroll;  cursor: auto;" autocomplete="off">
            <label for="url">Url do conteudo</label>
            <input type="url" name="url" id="url" class="form-control" style="background-repeat: no-repeat; background-attachment: scroll;" autocomplete="off">
            <label for="descricao" class="form-label">Descrição</label>
            <textarea name="descricao" id="descricao" class="form-control" maxlength="250"></textarea>
            <br />
            <button class="btn btn-primary" type="submit">Enviar</button>
            @*<input class="btn-primary" type="submit" value="Enviar" />*@
        </form>
    </div>

</div>