MonitoriaFatec/Controllers/CoordenadorController.cs
using MonitoriaFatec.DAO;
using MonitoriaFatec.Filtros;
using MonitoriaFatec.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonitoriaFatec.Controllers
{
    [AutorizacaoFilterAttribute]
    public class CoordenadorController : Controller
    {
        // GET: Coordenador
        public ActionResult Index()
        {
           

            return View();
        }

       
        public ActionResult Cadastro()
        {
            AtualizaCampos();
            return View();
        }

        public ActionResult Calendario()
        {
            AtualizaCampos();
            return View();
        }

        public ActionResult Materiais()
        {

            AtualizaCampos();
            return View();
        }

        public ActionResult Logout()
        {
            return RedirectToAction("Index","Login","Index");
        }

        public ActionResult CadastraDisciplina(String nome)
        {
            DISCIPLINE disciplina = new DISCIPLINE();
            disciplina.NMDISCIPLINE = nome;
            DisciplinaDAO dao = new DisciplinaDAO();
            dao.Cadastra(disciplina);
            AtualizaCampos();
            return View("Cadastro");
        }

        public ActionResult CadastraProfessor(String nome, String email)
        {
            UsuariosDAO daoUsuario = new UsuariosDAO();
            USUARIO professor = new USUARIO {
                NMUSER = nome,
                EMAILUSER = email,
                USERPASSWORD = email + "1234",
                IDSCOPE = 3
            };
            daoUsuario.Cadastra(professor);
            return View("Cadastro");
        }

        public ActionResult CadastraAluno(String nome, String email)
        {
            UsuariosDAO daoUsuario = new UsuariosDAO();
            USUARIO aluno = new USUARIO
            {
                NMUSER = nome,
                EMAILUSER = email,
                USERPASSWORD = email + "1234",
                IDSCOPE = 5
            };
            daoUsuario.Cadastra(aluno);
            AtualizaCampos();
            return View("Cadastro");
        }

        public void AtualizaCampos()
        {
            DisciplinaDAO daoDisciplina = new DisciplinaDAO();
            IList<DISCIPLINE> disciplinas = daoDisciplina.Lista();
            ViewBag.Disciplinas = disciplinas;

            CalendarioDao daoCalendario = new CalendarioDao();
            var agenda = daoCalendario.Lista();
            ViewBag.Agenda = agenda;

            ConteudoDAO daoConteudo = new ConteudoDAO();
            var conteudos = daoConteudo.Lista();
            ViewBag.Conteudos = conteudos;

        }
    }
}

MonitoriaFatec/Views/Coordenador/Cadastro.cshtml
@{
    ViewBag.Title = "Coordenador(a)";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Coordenador!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Coordenador")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Materiais", "Coordenador")"><i class="fa fa-fw fa-book"></i>Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Calendario", "Coordenador")"><i class="fa fa-fw fa-table"></i>Calendario Monitoria</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Cadastro", "Coordenador")"><i class="fa fa-fw fa-edit"></i>Cadastro de Alunos / Professores / Disciplina</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action( "Logout", "Coordenador")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Coordenador</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>

            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <div class="container-fluid">
        <form action="/Coordenador/CadastraProfessor" method="post">
            <h3>Cadastro de Professor</h3>
            <label for="inputHeader">Nome:</label>
            <input type="text" name="nome" id="inputHeader" class="form-control" required="" autofocus="" style="background-repeat: no-repeat; background-attachment: scroll;  cursor: auto;" autocomplete="off">
            <label for="inputReciver">Email</label>
            <input type="email" name="email" id="inputHeader" class="form-control" style="background-repeat: no-repeat; background-attachment: scroll;" autocomplete="off">
            <label for="inputDiscipline">Disciplina</label>
            <select class="form-control" id="inputDiscipline">
                @foreach (var disciplina in ViewBag.Disciplinas)
                {
                    <option id="@disciplina.IDDISCIPLINE">@disciplina.NMDISCIPLINE</option>
                }
                
            </select>
            <br />
            <button class="btn btn-primary" type="submit">Enviar</button>
            @*<input class="btn-primary" type="submit" value="Enviar" />*@
        </form>
    </div>
    <br />
    <br />
    <br />
    <div class="container-fluid">
        <form action="/Coordenador/CadastraAluno" method="post">
            <h3>Cadastro de Aluno</h3>
            <label for="inputHeader">Nome:</label>
            <input type="text" name="nome" id="inputHeader" class="form-control" required="" autofocus="" style="background-repeat: no-repeat; background-attachment: scroll;  cursor: auto;" autocomplete="off">
            <label for="inputReciver">Email</label>
            <input type="email" name="email" id="inputHeader" class="form-control" style="background-repeat: no-repeat; background-attachment: scroll;" autocomplete="off">
            <br />
            <button class="btn btn-primary" type="submit">Enviar</button>
            @*<input class="btn-primary" type="submit" value="Enviar" />*@
        </form>
    </div>
    <br />
    <br />
    <br />
    <div class="container-fluid">
        <form action="/Coordenador/CadastraDisciplina" method="post">
            <h3>Cadastro Disciplina</h3>
            <label for="nome">Nome:</label>
            <input type="text" name="nome" id="inputHeader" class="form-control" required="" autofocus="" style="background-repeat: no-repeat; background-attachment: scroll;  cursor: auto;" autocomplete="off">
           
            <br />
            <button class="btn btn-primary" type="submit">Enviar</button>
            @*<input class="btn-primary" type="submit" value="Enviar" />*@
        </form>
    </div>
</div>

MonitoriaFatec/Views/Coordenador/Calendario.cshtml
@{
    ViewBag.Title = "Coordenador(a)";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Coordenador!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Coordenador")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Materiais", "Coordenador")"><i class="fa fa-fw fa-book"></i>Materiais</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Calendario", "Coordenador")"><i class="fa fa-fw fa-table"></i>Calendario Monitoria</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastro", "Coordenador")"><i class="fa fa-fw fa-edit"></i>Cadastro de Alunos / Professores / Disciplina</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action( "Logout", "Coordenador")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Coordenador</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>

            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>


        <div class="container">
            <h2>Calendario</h2>
            <p>Calendario de Monitoria</p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Hora</th>
                            <th>Disciplina</th>
                            <th>Evento</th>
                            <th>Monitor</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var agenda in ViewBag.Agenda)
                        {
                            <tr>
                                <td>@agenda.hora</td>
                                <td>@agenda.data</td>
                                <td id="@agenda.idDisciplina">@agenda.disciplina</td>
                                <td>@agenda.evento</td>
                                <td id="@agenda.idMonitor">@agenda.monitor</td>
                                
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>

    </div>

    

MonitoriaFatec/Views/Coordenador/Index.cshtml
@{
    ViewBag.Title = "Coordenador(a)";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Coordenador!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Coordenador")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Materiais", "Coordenador")"><i class="fa fa-fw fa-book"></i>Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Calendario", "Coordenador")"><i class="fa fa-fw fa-table"></i>Calendario Monitoria</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastro", "Coordenador")"><i class="fa fa-fw fa-edit"></i>Cadastro de Alunos / Professores / Disciplina</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action( "Logout", "Coordenador")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Coordenador</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>

            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>

  
</div>

MonitoriaFatec/Views/Coordenador/Materiais.cshtml
@{
    ViewBag.Title = "Coordenador(a)";
}

<!-- Navigation -->
<nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bem Vindo Coordenador!</a>
    <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="sidebar-nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Coordenador")"><i class="fa fa-fw fa-dashboard"></i>Área de Trabalho</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link " href="@Url.Action("Materiais", "Coordenador")"><i class="fa fa-fw fa-book"></i>Materiais</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Calendario", "Coordenador")"><i class="fa fa-fw fa-table"></i>Calendario Monitoria</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cadastro", "Coordenador")"><i class="fa fa-fw fa-edit"></i>Cadastro de Alunos / Professores / Disciplina</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action( "Logout", "Coordenador")"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper py-3">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Área de Trabalho</a></li>
            <li class="breadcrumb-item active">Coordenador</li>
        </ol>
        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-primary o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">
                            26 Novas Mensagens!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>

            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card card-inverse card-danger o-hidden h-100">
                    <div class="card-block">
                        <div class="card-block-icon">
                            <i class="fa fa-fw fa-star"></i>
                        </div>
                        <div class="mr-5">
                            Conteudos Favoritos!
                        </div>
                    </div>
                    <a href="#" class="card-footer clearfix small z-1">
                        <span class="float-left">Verificar</span>
                        <span class="float-right"><i class="fa fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <div class="container">
        <h2>Materiais</h2>
        <p>Materiais de Apoio</p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Autor</th>
                        <th>URL</th>
                        <th>Data</th>
                        <th>Descrição</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var material in ViewBag.Conteudos)
                    {
                        
                        <tr>
                            <td>@material.TITLE</td>
                            <td>@material.IDAUTHOR</td>
                            <td>@material.CONTENT1</td>
                            <td>@material.DATECONTENT</td>
                            <td>@material.INFOCONTENT</td>
                        </tr>
                    }
                    
                </tbody>
            </table>
        </div>
    </div>